PROJECT=libdrv8835-rpi
UNAME=$(shell uname -s)
ARCH=$(shell uname -m)
TESTS=tests/
IS_RASPI=0
ifeq ($(UNAME), Linux)
  ifeq ($(ARCH), armv7l)
    IS_RASPI=1
  endif
endif

PUBLIC_LIB_HEADER=drv8835.h types.h drv8835_util.h
DAEMON_SOURCES=daemon/daemon.c
LIB_SOURCES=drv8835.c drv8835_util.c socket_client.c types.c common.c
ifeq ($(IS_RASPI), 1)
  LIB_SOURCES+=motor_server.c socket_server.c
endif
TEST_THREAD_SRC=$(TESTS)test_thread.c common.c drv8835_util.c
TEST_SOCKET_SRV_SRC=$(TESTS)test_socket_srv.c common.c drv8835_util.c types.c
TEST_SOCKET_CLT_SRC=$(TESTS)test_socket_clt.c common.c drv8835_util.c types.c
TEST_DRV8835_MOTOR_SERVER_SRC=$(TESTS)test_drv8835_motor_server.c
DRV8835_SERVER_SRC=drv8835_server.c
TEST_DRV8835_SOCKET_CLIENT_SRC=$(TESTS)test_drv8835_socket_client.c
DRV8835_SDL_CLIENT_SRC=sdl_client.c
SOURCES=$(DAEMON_SOURCES) $(LIB_SOURCES) $(TEST_THREAD_SRC) $(TEST_SOCKET_SRV_SRC) $(TEST_SOCKET_CLT_SRC) $(TEST_DRV8835_MOTOR_SERVER_SRC) $(DRV8835_SERVER_SRC) $(TEST_DRV8835_SOCKET_CLIENT_SRC) $(DRV8835_SDL_CLIENT_SRC)
INCPATHS=./ /usr/local/include/
LIBPATHS=./

LDFLAGS=-lpthread -pthread
ifeq ($(IS_RASPI), 1)
  LDFLAGS+=-lwiringPi
endif

SDL_LDFLAGS=-lSDL2
CFLAGS=-c -Wall
ifeq ($(IS_RASPI), 1)
  CFLAGS+=-DRASPI
endif
DRV8835_STATIC_LINKAGE=-Bstatic -ldrv8835
CC=gcc
AR=ar
ARFLAGS=rcs

# Automatic generation of some important lists
DAEMON_OBJECTS=$(DAEMON_SOURCES:.c=.o)
LIB_OBJECTS=$(LIB_SOURCES:.c=.o)
TEST_THREAD_OBJS=$(TEST_THREAD_SRC:.c=.o)
TEST_SOCKET_SRV_OBJS=$(TEST_SOCKET_SRV_SRC:.c=.o)
TEST_SOCKET_CLT_OBJS=$(TEST_SOCKET_CLT_SRC:.c=.o)
TEST_DRV8835_MOTOR_SERVER_OBJS=$(TEST_DRV8835_MOTOR_SERVER_SRC:.c=.o)
DRV8835_SERVER_OBJS=$(DRV8835_SERVER_SRC:.c=.o)
TEST_DRV8835_SOCKET_CLIENT_OBJS=$(TEST_DRV8835_SOCKET_CLIENT_SRC:.c=.o)
DRV8835_SDL_CLIENT_OBJS=$(DRV8835_SDL_CLIENT_SRC:.c=.o)
OBJECTS=$(DAEMON_OBJECTS) $(LIB_OBJECTS) $(TEST_THREAD_OBJS) $(TEST_SOCKET_SRV_OBJS) $(TEST_SOCKET_CLT_OBJS) $(TEST_DRV8835_MOTOR_SERVER_OBJS) $(DRV8835_SERVER_OBJS) $(TEST_DRV8835_SOCKET_CLIENT_OBJS) $(DRV8835_SDL_CLIENT_OBJS)
INCFLAGS=$(foreach TMP,$(INCPATHS),-I$(TMP)) 
LIBFLAGS=$(foreach TMP,$(LIBPATHS),-L$(TMP))

DAEMON_BINARY=daemon/drv8835_daemon
LIB_BIN=libdrv8835.a
# Shared library mainly for python
SHARED_LIB_BIN=libdrv8835.so
TEST_THREAD_BINARY=$(TESTS)drv8835_test_thread
TEST_SOCKET_SRV_BIN=$(TESTS)drv8835_test_socket_srv
TEST_SOCKET_CLT_BIN=$(TESTS)drv8835_test_socket_clt
TEST_DRV8835_MOTOR_SERVER_BIN=$(TESTS)drv8835_test_motor_server
DRV8835_SERVER_BIN=drv8835_server
TEST_DRV8835_SOCKET_CLIENT_BIN=$(TESTS)drv8835_test_socket_client
DRV8835_SDL_CLIENT_BIN=drv8835_sdl_client
ifeq ($(IS_RASPI), 1)
BINARY=$(DAEMON_BINARY) $(LIB_BIN) $(SHARED_LIB_BIN) $(TEST_THREAD_BINARY) $(TEST_SOCKET_SRV_BIN) $(TEST_SOCKET_CLT_BIN) $(TEST_DRV8835_MOTOR_SERVER_BIN) $(DRV8835_SERVER_BIN) $(TEST_DRV8835_SOCKET_CLIENT_BIN) $(DRV8835_SDL_CLIENT_BIN)
else
BINARY=$(LIB_BIN) $(SHARED_LIB_BIN) $(DRV8835_SDL_CLIENT_BIN) $(TEST_SOCKET_CLT_BIN) $(TEST_DRV8835_SOCKET_CLIENT_BIN)
endif
all: $(SOURCES) $(BINARY)

$(DAEMON_BINARY): $(DAEMON_OBJECTS)
	$(CC) $(LIBFLAGS) $(DAEMON_OBJECTS) $(LDFLAGS) -o $@
$(LIB_BIN): $(LIB_OBJECTS)
	$(AR) $(ARFLAGS) $@ $(LIB_OBJECTS)
$(SHARED_LIB_BIN): $(LIB_OBJECTS)
	$(CC) -shared -fPIC $(LDFLAGS) $(LIB_OBJECTS) -o $@
$(TEST_THREAD_BINARY): $(TEST_THREAD_OBJS)
	$(CC) $(LIBFLAGS) $(TEST_THREAD_OBJS) $(LDFLAGS) -o $@
$(TEST_SOCKET_SRV_BIN): $(TEST_SOCKET_SRV_OBJS)
	$(CC) $(LIBFLAGS) $(TEST_SOCKET_SRV_OBJS) $(LDFLAGS) -o $@
$(TEST_SOCKET_CLT_BIN): $(TEST_SOCKET_CLT_OBJS)
	$(CC) $(LIBFLAGS) $(TEST_SOCKET_CLT_OBJS) $(LDFLAGS) -o $@
$(TEST_DRV8835_MOTOR_SERVER_BIN): $(TEST_DRV8835_MOTOR_SERVER_OBJS) $(LIB_BIN)
	$(CC) $(LIBFLAGS) $(TEST_DRV8835_MOTOR_SERVER_OBJS) $(LDFLAGS) $(DRV8835_STATIC_LINKAGE) -o $@
$(DRV8835_SERVER_BIN): $(DRV8835_SERVER_OBJS) $(LIB_BIN)
	$(CC) $(LIBFLAGS) $(DRV8835_SERVER_OBJS) $(LDFLAGS) $(DRV8835_STATIC_LINKAGE) -o $@
$(TEST_DRV8835_SOCKET_CLIENT_BIN): $(TEST_DRV8835_SOCKET_CLIENT_OBJS) $(LIB_BIN)
	$(CC) $(LIBFLAGS) $(TEST_DRV8835_SOCKET_CLIENT_OBJS) $(LDFLAGS) $(DRV8835_STATIC_LINKAGE) -o $@
$(DRV8835_SDL_CLIENT_BIN): $(DRV8835_SDL_CLIENT_OBJS) $(LIB_BIN)
	$(CC) $(LIBFLAGS) $(DRV8835_SDL_CLIENT_OBJS) $(LDFLAGS) $(SDL_LDFLAGS) $(DRV8835_STATIC_LINKAGE) -o $@
.c.o:
	$(CC) $(INCFLAGS) $(CFLAGS) -fPIC $< -o $@

distclean: clean
	rm -f $(BINARY)

clean:
	rm -f $(OBJECTS)

install: $(BINARY)
	@echo Installing libdrv8835-rpi to system directory...
	cp $(SHARED_LIB_BIN) /usr/local/lib
	mkdir -p /usr/local/include/libdrv8835-rpi
	cp $(PUBLIC_LIB_HEADER) /usr/local/include/libdrv8835-rpi
